config/routes.rb
Semana1Ejercicio1Shop::Application.routes.draw do

  scope "/:locale" do

    get "home/index"
    root :to => "home#index"
    get "/sign_up" => "users#new", :as => "sign_up"
    get "/log_in" => "sessions#new", :as => "log_in"
    get "/sessions/:id" => "users#show"

    resources :orders
    resources :products
    resources :sessions
    resources :users

  end

  get '/', to: 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Para proteger las contraseñas por internet forzamos ssl
  #pero si lo activo me ignora el puerto, y me sale apache
  #force_ssl

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

#Sin la línea de abajo no puedo editar los usuarios / ordenes
 def default_url_options(options={})
   {:locale => I18n.locale}
 end

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def check_user_logged
    redirect_to log_in_path, notice: 'Log in first, please!' unless current_user
  end

  helper_method :current_user

end

app/helpers/application_helper.rb
module ApplicationHelper
    def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
    render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
    end
end

app/views/application/_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <%= link_to t("nav.home"), root_path, :class => "navbar-brand" %>
  <% if current_user %>
    <%= link_to t("nav.Products"), products_path, :class => "navbar-brand" %>
    <%= link_to t("nav.Orders"), orders_path, :class => "navbar-brand" %>
    <%= link_to t("nav.Users"), users_path, :class => "navbar-brand" %>
    <%= link_to "#{t('nav.Logged_in_as')} #{current_user.name}", user_path(id: current_user.id), :class => "navbar-brand" %>
    <%= link_to t("nav.Log_out"), session_path(id: current_user.id), method: :delete, data: { confirm: t("alert.Do_you_want_to_end_session")}, :class => "navbar-brand"   %>
  <% else %>
    <%= link_to t("nav.Sign_up"), sign_up_path, :class => "navbar-brand" %>
    <%= link_to t("nav.Log_in"), log_in_path, :class => "navbar-brand" %>
  <% end %>
</nav>

<nav class="navbar navbar-default navbar-fixed-bottom navbar-brand" role="navigation">
  <%= t('nav.locale')%> -->
  <%= link_to_if(params[:locale] != "en", "[EN]", {locale: :en}) %>
  <%= link_to_if(params[:locale] != "es", "[ES]", {locale: :es}) %>
  <%= link_to_if(params[:locale] != "ca", "[CA]", {locale: :ca}) %>
</nav>